---
# deploy-nextcloud-tasks.yml
- name: "Nextcloud Preparation"
  hosts: storage_nodes
  become: true
  # Add this line to pull in your variables
  vars_files:
    - "../group_vars/all.yml"
  tasks:
    - name: Create Nextcloud Secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: nextcloud-secrets
            namespace: nextcloud
          stringData:
            db-name: "{{ nextcloud_db_name }}"
            db-user: "{{ nextcloud_db_user }}"
            db-password: "{{ nextcloud_db_password }}"
            mariadb-root-password: "{{ mariadb_root_password }}"
            admin-user: "{{ nextcloud_admin_user }}"
            admin-password: "{{ nextcloud_admin_password }}"
            trusted-domains: "{{ nextcloud_trusted_domains }}"
            overwriteprotocol: "http"
            overwritehost: "{{ nextcloud_overwrite_host }}"
            overwritecliurl: "http://{{ nextcloud_overwrite_host }}"