---
- name: "Nextcloud Disk Preparation"
  hosts: storage_nodes
  become: true
  tasks:
    - name: Ensure Nextcloud directory exists on 450GB drive
      ansible.builtin.file:
        path: /mnt/media/nextcloud
        state: directory
        owner: "33"
        group: "33"
        mode: '0755'

- name: "Nextcloud Secret Preparation"
  hosts: localhost  # Run this part locally on the masternode
  connection: local
  become: true
  vars_files:
    - "../group_vars/all.yml"
  tasks:
    - name: Create Nextcloud Secrets in Cluster API
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: nextcloud-secrets
            namespace: nextcloud
          stringData:
            db-name: "{{ nextcloud_db_name }}"
            # ... (rest of your secret keys)